    LIST	P=16F887
    #INCLUDE    "p16f887.inc"

    __CONFIG    _CONFIG1, _INTOSCIO & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BOR_OFF & _LVP_OFF

W_TEMP	    EQU	0X70
STATUS_TEMP EQU	0X71
CONTADOR    EQU 0X72
CANAL	    EQU	0X73
CONTADOR2   EQU	0X74
CONTTIMER   EQU	0X75
CONTADOR3   EQU	0X76
CONTSAMPLE  EQU	0X77
ADCRESULT   EQU	0X78
	 
	ORG	    0X00
	GOTO	    MAIN
	ORG	    0X04
	GOTO	    ISR
	ORG	    0X05
MAIN
	BANKSEL	    ANSELH
	MOVLW	    B'00000111'
	MOVWF	    ANSEL
	CLRF	    ANSELH
	MOVLW	    .3
	MOVWF	    CONTADOR
	MOVLW	    B'00000111'
	BANKSEL	    TRISA
	MOVWF	    TRISA
	CLRF	    TRISB
	CLRF	    TRISC
	CLRF	    TRISE
	CLRF	    TRISD
	MOVLW	    .10
	MOVWF	    CONTTIMER
	BANKSEL	    TMR1L
	CLRF	    TMR1L
	CLRF	    TMR1H
	MOVLW	    B'00110001'
	MOVWF	    T1CON
	BANKSEL	    PIE1
	BSF	    PIE1,TMR1IE
	BSF	    INTCON,PEIE
	BANKSEL	    ADCON0
	MOVLW	    B'11000001'
	MOVWF	    ADCON0
	BANKSEL	    ADCON1
	MOVLW	    B'10000000'
	MOVWF	    ADCON1
	
	;ACA IRIA COMUNICACION SERIE
	
	BANKSEL	    TXSTA
	MOVLW	    B'00100100'
	MOVWF	    TXSTA
	BANKSEL	    BAUDCTL
	BCF	    BAUDCTL,BRG16
	BANKSEL	    SPBRG
	MOVLW	    .25
	MOVWF	    SPBRG
	BANKSEL	    RCSTA
	BSF	    RCSTA,SPEN
	
	;ACA IRIA COMUNICACION SERIE
	
	BCF	    STATUS,RP0
	BCF	    STATUS,RP1
	BSF	    INTCON,GIE
	CLRF	    PORTD
	CLRF	    PORTB
	CLRF	    PORTE
	GOTO	    $

	
	
ISR ;INTERRUPCION POR TIMER1
	MOVWF	    W_TEMP  ;GUARDAR CONTEXTO
	SWAPF	    STATUS,W
	MOVWF	    STATUS_TEMP
	
	DECFSZ	    CONTTIMER,F
	GOTO	    FINISH
	GOTO	    ADC
	
ADC	BCF	    STATUS,Z
	MOVLW	    .3
	SUBWF	    CONTADOR,W
	BTFSC	    STATUS,Z
	GOTO	    CANAL0_ADC
	MOVLW	    .2
	SUBWF	    CONTADOR,W
	BTFSC	    STATUS,Z
	GOTO	    CANAL1_ADC
	GOTO	    CANAL2_ADC
AFTER	CALL	    SAMPLETIME
	BSF	    ADCON0,GO
	BTFSC	    ADCON0,GO
	GOTO	    $-1
	BANKSEL	    ADRESL
	MOVF	    ADRESL,W
	MOVWF	    ADCRESULT

	CALL	    LED
	CALL	    COMSERIE
	
FINISH	BCF	    STATUS,RP0
	BCF	    STATUS,RP1
	CLRF	    TMR1L
	CLRF	    TMR1H
	BCF	    PIR1,TMR1IF
	
	;RECUPERAR CONTEXTO
	SWAPF	    STATUS_TEMP,W
	MOVWF	    STATUS
	SWAPF	    W_TEMP,F
	SWAPF	    W_TEMP,W
	RETFIE
	
	
CANAL0_ADC
	BCF	    PORTD,5
	BCF	    ADCON0,CHS0
	BCF	    ADCON0,CHS1
	BCF	    ADCON0,CHS2
	BCF	    ADCON0,CHS3
	MOVLW	    .2
	MOVWF	    CONTADOR
	BCF	    STATUS,Z
	MOVLW	    .1
	MOVWF	    CANAL
	BSF	    PORTD,3
	GOTO	    AFTER
	
CANAL1_ADC
	BCF	    PORTD,3
	BSF	    ADCON0,CHS0
	BCF	    ADCON0,CHS1
	BCF	    ADCON0,CHS2
	BCF	    ADCON0,CHS3
	MOVLW	    .1
	MOVWF	    CONTADOR
	BCF	    STATUS,Z
	MOVLW	    .2
	MOVWF	    CANAL
	BSF	    PORTD,4
	GOTO	    AFTER
	
CANAL2_ADC
	BCF	    PORTD,4
	BCF	    ADCON0,CHS0
	BSF	    ADCON0,CHS1
	BCF	    ADCON0,CHS2
	BCF	    ADCON0,CHS3
	MOVLW	    .3
	MOVWF	    CONTADOR
	BCF	    STATUS,Z
	MOVLW	    .3
	MOVWF	    CANAL
	BSF	    PORTD,5
	GOTO	    AFTER
	
LED
	BCF	    STATUS,C
	MOVLW	    .45
	SUBWF	    ADCRESULT,W
	BTFSS	    STATUS,C
	GOTO	    CANALA
	GOTO	    CANALP
CANALA	BCF	    STATUS,Z
	BANKSEL	    PORTD
	MOVLW	    .1
	SUBWF	    CANAL,W
	BTFSC	    STATUS,Z
	GOTO	    SELEC1A
	MOVLW	    .2
	SUBWF	    CANAL,W
	BTFSC	    STATUS,Z
	GOTO	    SELEC2A
	GOTO	    SELEC3A
SELEC1A	BCF	    PORTD,0
	GOTO	    AFTER2
SELEC2A	BCF	    PORTD,1
	GOTO	    AFTER2
SELEC3A	BCF	    PORTD,2
	GOTO	    AFTER2
CANALP	BCF	    STATUS,Z
	BANKSEL	    PORTD
	MOVLW	    .1
	SUBWF	    CANAL,W
	BTFSC	    STATUS,Z
	GOTO	    SELEC1P
	MOVLW	    .2
	SUBWF	    CANAL,W
	BTFSC	    STATUS,Z
	GOTO	    SELEC2P
	GOTO	    SELEC3P
SELEC1P	BSF	    PORTD,0
	GOTO	    AFTER2
SELEC2P	BSF	    PORTD,1
	GOTO	    AFTER2
SELEC3P	BSF	    PORTD,2
	GOTO	    AFTER2
AFTER2	MOVLW	    .10
	MOVWF	    CONTTIMER
	RETURN
	
COMSERIE
	MOVF	    ADCRESULT,W
	BANKSEL	    TXREG
	MOVWF	    TXREG
	BTFSS	    PIR1,TXIF
	GOTO	    $-1
	RETURN
	
SAMPLETIME  ;DELAY DE 12MICROSEG
	MOVLW	.4
	MOVWF	CONTSAMPLE
	DECFSZ	CONTSAMPLE,F
	GOTO $-1
	RETURN
	
	END